services:
  - type: web
    name: dtpa-bingo
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy:
      ignoredPaths:
        - "**/*.md"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
